// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWorkspace'](arg1, arg2, arg3, arg4);
}

export function AnswerApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerApproval'](arg1, arg2, arg3);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateSummarizedSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSummarizedSession'](arg1, arg2, arg3);
}

export function CreateToolProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateToolProfile'](arg1, arg2, arg3);
}

export function DeleteDBProvider(arg1) {
  return window['go']['main']['App']['DeleteDBProvider'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSpecWizard(arg1) {
  return window['go']['main']['App']['DeleteSpecWizard'](arg1);
}

export function DeleteToolProfile(arg1) {
  return window['go']['main']['App']['DeleteToolProfile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DeleteWorkspaceTemplate(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceTemplate'](arg1);
}

export function FetchProviderModels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2, arg3, arg4);
}

export function GetAdaConfig() {
  return window['go']['main']['App']['GetAdaConfig']();
}

export function GetAgentCategories() {
  return window['go']['main']['App']['GetAgentCategories']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetArchitectures() {
  return window['go']['main']['App']['GetArchitectures']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetEnvProviderKeys() {
  return window['go']['main']['App']['GetEnvProviderKeys']();
}

export function GetExperts() {
  return window['go']['main']['App']['GetExperts']();
}

export function GetInstalledSkills() {
  return window['go']['main']['App']['GetInstalledSkills']();
}

export function GetPatterns(arg1) {
  return window['go']['main']['App']['GetPatterns'](arg1);
}

export function GetPredefinedConnections() {
  return window['go']['main']['App']['GetPredefinedConnections']();
}

export function GetProvidersConfig() {
  return window['go']['main']['App']['GetProvidersConfig']();
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSkillDetails(arg1) {
  return window['go']['main']['App']['GetSkillDetails'](arg1);
}

export function GetSkillFullInfo(arg1) {
  return window['go']['main']['App']['GetSkillFullInfo'](arg1);
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSpecWizard(arg1) {
  return window['go']['main']['App']['GetSpecWizard'](arg1);
}

export function GetSpecWizards() {
  return window['go']['main']['App']['GetSpecWizards']();
}

export function GetStacks(arg1) {
  return window['go']['main']['App']['GetStacks'](arg1);
}

export function GetStateManagement(arg1) {
  return window['go']['main']['App']['GetStateManagement'](arg1);
}

export function GetToolProfiles() {
  return window['go']['main']['App']['GetToolProfiles']();
}

export function GetWorkerCategories() {
  return window['go']['main']['App']['GetWorkerCategories']();
}

export function GetWorkers() {
  return window['go']['main']['App']['GetWorkers']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function GetWorkspaceTemplates() {
  return window['go']['main']['App']['GetWorkspaceTemplates']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function InstallMCPFromRepo(arg1) {
  return window['go']['main']['App']['InstallMCPFromRepo'](arg1);
}

export function InstallSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2, arg3);
}

export function ListAllCommands() {
  return window['go']['main']['App']['ListAllCommands']();
}

export function ListChatCommands() {
  return window['go']['main']['App']['ListChatCommands']();
}

export function ListChatProviders() {
  return window['go']['main']['App']['ListChatProviders']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RetryMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryMessage'](arg1, arg2);
}

export function SaveCustomSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCustomSkill'](arg1, arg2, arg3, arg4);
}

export function SaveDBProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveDBProvider'](arg1, arg2);
}

export function SaveProvidersConfig() {
  return window['go']['main']['App']['SaveProvidersConfig']();
}

export function SaveSpecWizard(arg1) {
  return window['go']['main']['App']['SaveSpecWizard'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SaveWorkspaceTemplate(arg1) {
  return window['go']['main']['App']['SaveWorkspaceTemplate'](arg1);
}

export function SearchMCPServers(arg1) {
  return window['go']['main']['App']['SearchMCPServers'](arg1);
}

export function SearchSkills(arg1) {
  return window['go']['main']['App']['SearchSkills'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetAdaConfig(arg1) {
  return window['go']['main']['App']['SetAdaConfig'](arg1);
}

export function SetAgentCategories(arg1) {
  return window['go']['main']['App']['SetAgentCategories'](arg1);
}

export function SetAgents(arg1) {
  return window['go']['main']['App']['SetAgents'](arg1);
}

export function SetFixedModelTools(arg1, arg2) {
  return window['go']['main']['App']['SetFixedModelTools'](arg1, arg2);
}

export function SetSessionConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetSessionConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetWorkerCategories(arg1) {
  return window['go']['main']['App']['SetWorkerCategories'](arg1);
}

export function SetWorkers(arg1) {
  return window['go']['main']['App']['SetWorkers'](arg1);
}

export function SetWorkspaces(arg1) {
  return window['go']['main']['App']['SetWorkspaces'](arg1);
}

export function StopGeneration(arg1) {
  return window['go']['main']['App']['StopGeneration'](arg1);
}

export function SuggestFieldValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuggestFieldValue'](arg1, arg2, arg3);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function TestMCPConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMCPConnection'](arg1, arg2, arg3, arg4);
}

export function TestProviderConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestProviderConnection'](arg1, arg2, arg3, arg4);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function ToggleProfileTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleProfileTool'](arg1, arg2, arg3);
}

export function ToggleTool(arg1, arg2) {
  return window['go']['main']['App']['ToggleTool'](arg1, arg2);
}

export function ToggleWorkspace(arg1) {
  return window['go']['main']['App']['ToggleWorkspace'](arg1);
}

export function UninstallSkill(arg1) {
  return window['go']['main']['App']['UninstallSkill'](arg1);
}

export function UpdateSkillConfig(arg1) {
  return window['go']['main']['App']['UpdateSkillConfig'](arg1);
}
