// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {tool} from '../models';
import {provider} from '../models';
import {ada} from '../models';
import {agent} from '../models';
import {mcp} from '../models';
import {skill} from '../models';
import {specwizard} from '../models';
import {worker} from '../models';
import {workspace} from '../models';
import {command} from '../models';
import {main} from '../models';

export function AddWorkspace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function AnswerQuestion(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:string):Promise<core.Session>;

export function CreateSummarizedSession(arg1:string,arg2:string,arg3:string):Promise<core.Session>;

export function CreateToolProfile(arg1:string,arg2:string,arg3:string):Promise<tool.ToolProfile>;

export function DeleteDBProvider(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSpecWizard(arg1:string):Promise<void>;

export function DeleteToolProfile(arg1:number):Promise<boolean>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DeleteWorkspaceTemplate(arg1:number):Promise<void>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<provider.ProviderModel>>;

export function GetAdaConfig():Promise<ada.AdaConfig>;

export function GetAgentCategories():Promise<Array<string>>;

export function GetAgents():Promise<Array<agent.AgentConfig>>;

export function GetArchitectures():Promise<Array<Record<string, any>>>;

export function GetAvailableTools():Promise<Array<tool.ToolUIInfo>>;

export function GetEnvProviderKeys():Promise<Array<string>>;

export function GetExperts():Promise<Array<Record<string, any>>>;

export function GetInstalledSkills():Promise<Array<string>>;

export function GetPatterns(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPredefinedConnections():Promise<Array<mcp.ConnectionDefinition>>;

export function GetProvidersConfig():Promise<Record<string, provider.ProviderConfig>>;

export function GetSessions(arg1:string):Promise<Array<core.Session>>;

export function GetSkillDetails(arg1:string):Promise<string>;

export function GetSkillFullInfo(arg1:string):Promise<skill.SkillFullInfo>;

export function GetSkills():Promise<Array<skill.SkillConfig>>;

export function GetSpecWizard(arg1:string):Promise<specwizard.SpecWizardConfig>;

export function GetSpecWizards():Promise<Array<specwizard.SpecWizardConfig>>;

export function GetStacks(arg1:string):Promise<Array<Record<string, any>>>;

export function GetStateManagement(arg1:string):Promise<Array<Record<string, any>>>;

export function GetToolProfiles():Promise<Array<tool.ToolProfile>>;

export function GetWorkerCategories():Promise<Array<string>>;

export function GetWorkers():Promise<Array<worker.WorkerConfig>>;

export function GetWorkspace(arg1:string):Promise<workspace.WorkspaceConfig>;

export function GetWorkspaceTemplates():Promise<Array<workspace.WorkspaceTemplate>>;

export function GetWorkspaces():Promise<Array<workspace.WorkspaceConfig>>;

export function InstallMCPFromRepo(arg1:string):Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAllCommands():Promise<Array<tool.ToolUIInfo>>;

export function ListChatCommands():Promise<Array<tool.ToolUIInfo>>;

export function ListChatProviders():Promise<Array<string>>;

export function ListCommands():Promise<Array<command.CommandInfo>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RemoveModel(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<core.Session>;

export function RetryMessage(arg1:string,arg2:string):Promise<string>;

export function SaveCustomSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveDBProvider(arg1:string,arg2:provider.ProviderConfig):Promise<void>;

export function SaveProvidersConfig():Promise<void>;

export function SaveSpecWizard(arg1:specwizard.SpecWizardConfig):Promise<void>;

export function SaveWorkspace(arg1:workspace.WorkspaceConfig):Promise<void>;

export function SaveWorkspaceTemplate(arg1:workspace.WorkspaceTemplate):Promise<void>;

export function SearchMCPServers(arg1:string):Promise<Array<main.MCPServerRegistry>>;

export function SearchSkills(arg1:string):Promise<Array<skill.SearchResult>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SetActiveWorkspace(arg1:string):Promise<void>;

export function SetAdaConfig(arg1:ada.AdaConfig):Promise<void>;

export function SetAgentCategories(arg1:Array<string>):Promise<void>;

export function SetAgents(arg1:Array<agent.AgentConfig>):Promise<void>;

export function SetFixedModelTools(arg1:string,arg2:Array<string>):Promise<boolean>;

export function SetSessionConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetWorkerCategories(arg1:Array<string>):Promise<void>;

export function SetWorkers(arg1:Array<worker.WorkerConfig>):Promise<void>;

export function SetWorkspaces(arg1:Array<workspace.WorkspaceConfig>):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function SuggestFieldValue(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<mcp.ConnectionTestResult>;

export function TestMCPConnection(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<mcp.ConnectionTestResult>;

export function TestProviderConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<provider.ProviderTestResult>;

export function TogglePin(arg1:string):Promise<void>;

export function ToggleProfileTool(arg1:number,arg2:string,arg3:boolean):Promise<boolean>;

export function ToggleTool(arg1:string,arg2:boolean):Promise<boolean>;

export function ToggleWorkspace(arg1:string):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;

export function UpdateSkillConfig(arg1:skill.SkillConfig):Promise<void>;
