// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {specwizard} from '../models';
import {core} from '../models';
import {tool} from '../models';
import {provider} from '../models';
import {ada} from '../models';
import {agent} from '../models';
import {specwizardmgr} from '../models';
import {cliworker} from '../models';
import {urlworker} from '../models';
import {mcp} from '../models';
import {engine} from '../models';
import {worker} from '../models';
import {skill} from '../models';
import {workspace} from '../models';
import {command} from '../models';
import {main} from '../models';

export function AddSessionAttachment(arg1:string,arg2:string):Promise<storage.SessionAttachment>;

export function AddWorkerToWorkspace(arg1:string,arg2:string):Promise<void>;

export function AddWorkspace(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AnswerApproval(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function AnswerQuestion(arg1:string,arg2:string):Promise<void>;

export function CheckAttachmentExists(arg1:string,arg2:string):Promise<boolean>;

export function ComputeHealth(arg1:specwizard.SpecWizardConfig):Promise<number>;

export function CountWorkerSessions(arg1:string,arg2:string):Promise<number>;

export function CreateSession(arg1:string,arg2:string):Promise<core.Session>;

export function CreateSessionWithConfig(arg1:string,arg2:string,arg3:string):Promise<core.Session>;

export function CreateSummarizedSession(arg1:string,arg2:string,arg3:string):Promise<core.Session>;

export function CreateToolProfile(arg1:string,arg2:string,arg3:string):Promise<tool.ToolProfile>;

export function DeleteDBProvider(arg1:string):Promise<void>;

export function DeleteFixedModel(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSpecWizard(arg1:string):Promise<void>;

export function DeleteToolProfile(arg1:number):Promise<boolean>;

export function DeleteWorkerProvider(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DeleteWorkspaceTemplate(arg1:number):Promise<void>;

export function EnsureWorkspaceSummary(arg1:string):Promise<void>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<provider.ProviderModel>>;

export function GenerateWorkspaceSummary(arg1:string):Promise<string>;

export function GetAdaConfig():Promise<ada.AdaConfig>;

export function GetAgentCategories():Promise<Array<string>>;

export function GetAgents():Promise<Array<agent.AgentConfig>>;

export function GetArchitectures():Promise<Array<specwizardmgr.Option>>;

export function GetAvailableTools():Promise<Array<tool.ToolUIInfo>>;

export function GetCLIModels(arg1:string):Promise<Array<cliworker.ModelInfo>>;

export function GetDataPatterns(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetDesignPatterns(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetEngineeringPhilosophies(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetEnvProviderKeys():Promise<Array<string>>;

export function GetExperts():Promise<Array<Record<string, any>>>;

export function GetFixedModels():Promise<Array<Record<string, any>>>;

export function GetInstalledSkills():Promise<Array<string>>;

export function GetOpenCodeModels(arg1:string):Promise<Array<urlworker.ModelInfo>>;

export function GetPatterns(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetPersistenceOptions(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetPredefinedConnections():Promise<Array<mcp.ConnectionDefinition>>;

export function GetProvidersByWorker(arg1:string):Promise<Record<string, provider.ProviderConfig>>;

export function GetProvidersConfig():Promise<Record<string, provider.ProviderConfig>>;

export function GetRecommendations(arg1:specwizard.SpecWizardConfig):Promise<Array<specwizardmgr.Recommendation>>;

export function GetSessionByID(arg1:string):Promise<core.Session>;

export function GetSessionContextInfo(arg1:string):Promise<engine.ContextInfo>;

export function GetSessionDir(arg1:string):Promise<string>;

export function GetSessionMessages(arg1:string):Promise<Array<core.RawMessage>>;

export function GetSessionWorker(arg1:string):Promise<worker.WorkerConfig>;

export function GetSessionWorkspaceSpec(arg1:string):Promise<specwizard.SpecWizardConfig>;

export function GetSessions(arg1:string):Promise<Array<core.Session>>;

export function GetSkillDetails(arg1:string):Promise<string>;

export function GetSkillFullInfo(arg1:string):Promise<skill.SkillFullInfo>;

export function GetSkills():Promise<Array<skill.SkillConfig>>;

export function GetSpecWizard(arg1:string):Promise<specwizard.SpecWizardConfig>;

export function GetSpecWizards():Promise<Array<specwizard.SpecWizardConfig>>;

export function GetStacks(arg1:string):Promise<Array<Record<string, any>>>;

export function GetStateManagement(arg1:string):Promise<Array<specwizardmgr.Option>>;

export function GetToolProfiles():Promise<Array<tool.ToolProfile>>;

export function GetURLModels(arg1:string):Promise<Array<urlworker.ModelInfo>>;

export function GetURLWorkerStatus(arg1:string):Promise<Record<string, any>>;

export function GetWorkerCategories():Promise<Array<string>>;

export function GetWorkers():Promise<Array<worker.WorkerConfig>>;

export function GetWorkspace(arg1:string):Promise<workspace.WorkspaceConfig>;

export function GetWorkspaceDir(arg1:string):Promise<string>;

export function GetWorkspaceSpec(arg1:string):Promise<specwizard.SpecWizardConfig>;

export function GetWorkspaceTemplates():Promise<Array<workspace.WorkspaceTemplate>>;

export function GetWorkspaces():Promise<Array<workspace.WorkspaceConfig>>;

export function GitAdd(arg1:string,arg2:string):Promise<string>;

export function GitBranchCheckout(arg1:string,arg2:string):Promise<string>;

export function GitBranchCreate(arg1:string,arg2:string):Promise<string>;

export function GitBranchList(arg1:string):Promise<string>;

export function GitCommit(arg1:string,arg2:string):Promise<string>;

export function GitDiff(arg1:string):Promise<string>;

export function GitInferCommitMessage(arg1:string):Promise<string>;

export function GitInit(arg1:string):Promise<string>;

export function GitLog(arg1:string,arg2:number):Promise<string>;

export function GitPull(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GitPush(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GitRemoteAdd(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitRemoteList(arg1:string):Promise<string>;

export function GitStatus(arg1:string):Promise<string>;

export function InferField(arg1:string,arg2:specwizard.SpecWizardConfig):Promise<string>;

export function InstallMCPFromRepo(arg1:string):Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAllCommands():Promise<Array<tool.ToolUIInfo>>;

export function ListChatCommands():Promise<Array<tool.ToolUIInfo>>;

export function ListChatProviders():Promise<Array<string>>;

export function ListCommands():Promise<Array<command.CommandInfo>>;

export function ListProvidersByWorker(arg1:string):Promise<Record<string, provider.ProviderConfig>>;

export function ListSessionAttachments(arg1:string):Promise<Array<storage.SessionAttachment>>;

export function ListWorkspaceWorkers(arg1:string):Promise<Array<worker.WorkerConfig>>;

export function NextChatName(arg1:string,arg2:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RemoveModel(arg1:string,arg2:string):Promise<void>;

export function RemoveSessionAttachment(arg1:string,arg2:string):Promise<void>;

export function RemoveWorkerFromWorkspace(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<core.Session>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function RetryMessage(arg1:string,arg2:string):Promise<string>;

export function SaveCustomSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveDBProvider(arg1:string,arg2:provider.ProviderConfig):Promise<void>;

export function SaveFixedModel(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SaveProvidersConfig():Promise<void>;

export function SaveSpecWizard(arg1:specwizard.SpecWizardConfig):Promise<void>;

export function SaveWorkerProvider(arg1:string,arg2:string,arg3:provider.ProviderConfig):Promise<void>;

export function SaveWorkspace(arg1:workspace.WorkspaceConfig):Promise<void>;

export function SaveWorkspaceTemplate(arg1:workspace.WorkspaceTemplate):Promise<void>;

export function SearchMCPServers(arg1:string):Promise<Array<main.MCPServerRegistry>>;

export function SearchSkills(arg1:string):Promise<Array<skill.SearchResult>>;

export function SendCLIMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SendOpenCodeMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendURLMessage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetActiveWorkspace(arg1:string):Promise<void>;

export function SetAdaConfig(arg1:ada.AdaConfig):Promise<void>;

export function SetAgentCategories(arg1:Array<string>):Promise<void>;

export function SetAgents(arg1:Array<agent.AgentConfig>):Promise<void>;

export function SetFixedModelTools(arg1:string,arg2:Array<string>):Promise<boolean>;

export function SetSessionConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetWorkerCategories(arg1:Array<string>):Promise<void>;

export function SetWorkers(arg1:Array<worker.WorkerConfig>):Promise<void>;

export function SetWorkspaces(arg1:Array<workspace.WorkspaceConfig>):Promise<void>;

export function StartURLWorkerServer(arg1:string):Promise<void>;

export function StopGeneration(arg1:string):Promise<void>;

export function StopURLWorkerServer(arg1:string):Promise<void>;

export function SyncSpecToWorkspaceBySession(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<mcp.ConnectionTestResult>;

export function TestMCPConnection(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<mcp.ConnectionTestResult>;

export function TestProviderConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<provider.ProviderTestResult>;

export function TogglePin(arg1:string):Promise<void>;

export function ToggleProfileTool(arg1:number,arg2:string,arg3:boolean):Promise<boolean>;

export function ToggleTool(arg1:string,arg2:boolean):Promise<boolean>;

export function ToggleWorkspace(arg1:string):Promise<void>;

export function UninstallSkill(arg1:string):Promise<void>;

export function UpdateSkillConfig(arg1:skill.SkillConfig):Promise<void>;
