// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkerToWorkspace(arg1, arg2) {
  return window['go']['main']['App']['AddWorkerToWorkspace'](arg1, arg2);
}

export function AddWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWorkspace'](arg1, arg2, arg3, arg4);
}

export function AnswerApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerApproval'](arg1, arg2, arg3);
}

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function ComputeHealth(arg1) {
  return window['go']['main']['App']['ComputeHealth'](arg1);
}

export function CountWorkerSessions(arg1, arg2) {
  return window['go']['main']['App']['CountWorkerSessions'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateSessionWithConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSessionWithConfig'](arg1, arg2, arg3);
}

export function CreateSummarizedSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSummarizedSession'](arg1, arg2, arg3);
}

export function CreateToolProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateToolProfile'](arg1, arg2, arg3);
}

export function DeleteDBProvider(arg1) {
  return window['go']['main']['App']['DeleteDBProvider'](arg1);
}

export function DeleteFixedModel(arg1) {
  return window['go']['main']['App']['DeleteFixedModel'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSpecWizard(arg1) {
  return window['go']['main']['App']['DeleteSpecWizard'](arg1);
}

export function DeleteToolProfile(arg1) {
  return window['go']['main']['App']['DeleteToolProfile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function DeleteWorkspaceTemplate(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceTemplate'](arg1);
}

export function FetchProviderModels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2, arg3, arg4);
}

export function GetAdaConfig() {
  return window['go']['main']['App']['GetAdaConfig']();
}

export function GetAgentCategories() {
  return window['go']['main']['App']['GetAgentCategories']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetArchitectures() {
  return window['go']['main']['App']['GetArchitectures']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetDataPatterns(arg1) {
  return window['go']['main']['App']['GetDataPatterns'](arg1);
}

export function GetDesignPatterns(arg1) {
  return window['go']['main']['App']['GetDesignPatterns'](arg1);
}

export function GetEngineeringPhilosophies(arg1) {
  return window['go']['main']['App']['GetEngineeringPhilosophies'](arg1);
}

export function GetEnvProviderKeys() {
  return window['go']['main']['App']['GetEnvProviderKeys']();
}

export function GetExperts() {
  return window['go']['main']['App']['GetExperts']();
}

export function GetFixedModels() {
  return window['go']['main']['App']['GetFixedModels']();
}

export function GetInstalledSkills() {
  return window['go']['main']['App']['GetInstalledSkills']();
}

export function GetPatterns(arg1) {
  return window['go']['main']['App']['GetPatterns'](arg1);
}

export function GetPersistenceOptions(arg1) {
  return window['go']['main']['App']['GetPersistenceOptions'](arg1);
}

export function GetPredefinedConnections() {
  return window['go']['main']['App']['GetPredefinedConnections']();
}

export function GetProvidersConfig() {
  return window['go']['main']['App']['GetProvidersConfig']();
}

export function GetRecommendations(arg1) {
  return window['go']['main']['App']['GetRecommendations'](arg1);
}

export function GetSessionByID(arg1) {
  return window['go']['main']['App']['GetSessionByID'](arg1);
}

export function GetSessionContextInfo(arg1) {
  return window['go']['main']['App']['GetSessionContextInfo'](arg1);
}

export function GetSessionDir(arg1) {
  return window['go']['main']['App']['GetSessionDir'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetSessionWorkspaceSpec(arg1) {
  return window['go']['main']['App']['GetSessionWorkspaceSpec'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSkillDetails(arg1) {
  return window['go']['main']['App']['GetSkillDetails'](arg1);
}

export function GetSkillFullInfo(arg1) {
  return window['go']['main']['App']['GetSkillFullInfo'](arg1);
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetSpecWizard(arg1) {
  return window['go']['main']['App']['GetSpecWizard'](arg1);
}

export function GetSpecWizards() {
  return window['go']['main']['App']['GetSpecWizards']();
}

export function GetStacks(arg1) {
  return window['go']['main']['App']['GetStacks'](arg1);
}

export function GetStateManagement(arg1) {
  return window['go']['main']['App']['GetStateManagement'](arg1);
}

export function GetToolProfiles() {
  return window['go']['main']['App']['GetToolProfiles']();
}

export function GetWorkerCategories() {
  return window['go']['main']['App']['GetWorkerCategories']();
}

export function GetWorkers() {
  return window['go']['main']['App']['GetWorkers']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function GetWorkspaceDir(arg1) {
  return window['go']['main']['App']['GetWorkspaceDir'](arg1);
}

export function GetWorkspaceSpec(arg1) {
  return window['go']['main']['App']['GetWorkspaceSpec'](arg1);
}

export function GetWorkspaceTemplates() {
  return window['go']['main']['App']['GetWorkspaceTemplates']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function GitAdd(arg1, arg2) {
  return window['go']['main']['App']['GitAdd'](arg1, arg2);
}

export function GitBranchCheckout(arg1, arg2) {
  return window['go']['main']['App']['GitBranchCheckout'](arg1, arg2);
}

export function GitBranchCreate(arg1, arg2) {
  return window['go']['main']['App']['GitBranchCreate'](arg1, arg2);
}

export function GitBranchList(arg1) {
  return window['go']['main']['App']['GitBranchList'](arg1);
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitDiff(arg1) {
  return window['go']['main']['App']['GitDiff'](arg1);
}

export function GitInferCommitMessage(arg1) {
  return window['go']['main']['App']['GitInferCommitMessage'](arg1);
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['App']['GitLog'](arg1, arg2);
}

export function GitPull(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPull'](arg1, arg2, arg3, arg4);
}

export function GitPush(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GitPush'](arg1, arg2, arg3, arg4);
}

export function GitRemoteAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitRemoteAdd'](arg1, arg2, arg3);
}

export function GitRemoteList(arg1) {
  return window['go']['main']['App']['GitRemoteList'](arg1);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function InferField(arg1, arg2) {
  return window['go']['main']['App']['InferField'](arg1, arg2);
}

export function InstallMCPFromRepo(arg1) {
  return window['go']['main']['App']['InstallMCPFromRepo'](arg1);
}

export function InstallSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2, arg3);
}

export function ListAllCommands() {
  return window['go']['main']['App']['ListAllCommands']();
}

export function ListChatCommands() {
  return window['go']['main']['App']['ListChatCommands']();
}

export function ListChatProviders() {
  return window['go']['main']['App']['ListChatProviders']();
}

export function ListCommands() {
  return window['go']['main']['App']['ListCommands']();
}

export function ListWorkspaceWorkers(arg1) {
  return window['go']['main']['App']['ListWorkspaceWorkers'](arg1);
}

export function NextChatName(arg1, arg2) {
  return window['go']['main']['App']['NextChatName'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveModel(arg1, arg2) {
  return window['go']['main']['App']['RemoveModel'](arg1, arg2);
}

export function RemoveWorkerFromWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorkerFromWorkspace'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function RetryMessage(arg1, arg2) {
  return window['go']['main']['App']['RetryMessage'](arg1, arg2);
}

export function SaveCustomSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCustomSkill'](arg1, arg2, arg3, arg4);
}

export function SaveDBProvider(arg1, arg2) {
  return window['go']['main']['App']['SaveDBProvider'](arg1, arg2);
}

export function SaveFixedModel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFixedModel'](arg1, arg2, arg3, arg4);
}

export function SaveProvidersConfig() {
  return window['go']['main']['App']['SaveProvidersConfig']();
}

export function SaveSpecWizard(arg1) {
  return window['go']['main']['App']['SaveSpecWizard'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SaveWorkspaceTemplate(arg1) {
  return window['go']['main']['App']['SaveWorkspaceTemplate'](arg1);
}

export function SearchMCPServers(arg1) {
  return window['go']['main']['App']['SearchMCPServers'](arg1);
}

export function SearchSkills(arg1) {
  return window['go']['main']['App']['SearchSkills'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetAdaConfig(arg1) {
  return window['go']['main']['App']['SetAdaConfig'](arg1);
}

export function SetAgentCategories(arg1) {
  return window['go']['main']['App']['SetAgentCategories'](arg1);
}

export function SetAgents(arg1) {
  return window['go']['main']['App']['SetAgents'](arg1);
}

export function SetFixedModelTools(arg1, arg2) {
  return window['go']['main']['App']['SetFixedModelTools'](arg1, arg2);
}

export function SetSessionConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetSessionConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SetWorkerCategories(arg1) {
  return window['go']['main']['App']['SetWorkerCategories'](arg1);
}

export function SetWorkers(arg1) {
  return window['go']['main']['App']['SetWorkers'](arg1);
}

export function SetWorkspaces(arg1) {
  return window['go']['main']['App']['SetWorkspaces'](arg1);
}

export function StopGeneration(arg1) {
  return window['go']['main']['App']['StopGeneration'](arg1);
}

export function SyncSpecToWorkspaceBySession(arg1) {
  return window['go']['main']['App']['SyncSpecToWorkspaceBySession'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function TestMCPConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestMCPConnection'](arg1, arg2, arg3, arg4);
}

export function TestProviderConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestProviderConnection'](arg1, arg2, arg3, arg4);
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function ToggleProfileTool(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleProfileTool'](arg1, arg2, arg3);
}

export function ToggleTool(arg1, arg2) {
  return window['go']['main']['App']['ToggleTool'](arg1, arg2);
}

export function ToggleWorkspace(arg1) {
  return window['go']['main']['App']['ToggleWorkspace'](arg1);
}

export function UninstallSkill(arg1) {
  return window['go']['main']['App']['UninstallSkill'](arg1);
}

export function UpdateSkillConfig(arg1) {
  return window['go']['main']['App']['UpdateSkillConfig'](arg1);
}
